/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from '../../../../src/app/components/error.component';
const styles_ErrorComponent:any[] = ([] as any[]);
export const RenderType_ErrorComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ErrorComponent,data:{}});
export function View_ErrorComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),23,'div',[['class',
      'col-lg-8 col-lg-offest-1']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n	'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),20,'div',[['class','jumbotron']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['',''])),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['La página que intentas cargar no existe. Prueba con estos botones:'])),
      (_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          11,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n			'])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),3,'a',[['class','btn btn-lg btn-primary']],[[1,
              'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,13).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),i0.ɵpad(1),(_l()(),i0.ɵted((null as any),['Ver productos'])),
      (_l()(),i0.ɵted((null as any),['\n			'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          3,'a',[['class','btn btn-lg btn-success']],[[1,'target',0],[8,'href',4]],
          [[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,18).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),i0.ɵpad(1),(_l()(),i0.ɵted((null as any),['Añadir productos'])),
      (_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵted((null as any),['\n	'])),
      (_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    const currVal_3:any = _ck(_v,14,0,'/productos');
    _ck(_v,13,0,currVal_3);
    const currVal_6:any = _ck(_v,19,0,'/crear-producto');
    _ck(_v,18,0,currVal_6);
  },(_ck,_v) => {
    var _co:i3.ErrorComponent = _v.component;
    const currVal_0:any = _co.titulo;
    _ck(_v,5,0,currVal_0);
    const currVal_1:any = i0.ɵnov(_v,13).target;
    const currVal_2:any = i0.ɵnov(_v,13).href;
    _ck(_v,12,0,currVal_1,currVal_2);
    const currVal_4:any = i0.ɵnov(_v,18).target;
    const currVal_5:any = i0.ɵnov(_v,18).href;
    _ck(_v,17,0,currVal_4,currVal_5);
  });
}
export function View_ErrorComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'error',([] as any[]),
      (null as any),(null as any),(null as any),View_ErrorComponent_0,RenderType_ErrorComponent)),
      i0.ɵdid(114688,(null as any),0,i3.ErrorComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ErrorComponentNgFactory:i0.ComponentFactory<i3.ErrorComponent> = i0.ɵccf('error',
    i3.ErrorComponent,View_ErrorComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3Jlc3RyYWRhei9hbmd1bGFyLXdlYnBhY2svd2VicGFjay1hbmd1bGFyNC9zcmMvYXBwL2NvbXBvbmVudHMvZXJyb3IuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3Jlc3RyYWRhei9hbmd1bGFyLXdlYnBhY2svd2VicGFjay1hbmd1bGFyNC9zcmMvYXBwL2NvbXBvbmVudHMvZXJyb3IuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvcmVzdHJhZGF6L2FuZ3VsYXItd2VicGFjay93ZWJwYWNrLWFuZ3VsYXI0L3NyYy9hcHAvdmlld3MvZXJyb3IuaHRtbCIsIm5nOi8vL1VzZXJzL3Jlc3RyYWRhei9hbmd1bGFyLXdlYnBhY2svd2VicGFjay1hbmd1bGFyNC9zcmMvYXBwL2NvbXBvbmVudHMvZXJyb3IuY29tcG9uZW50LnRzLkVycm9yQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNvbC1sZy04IGNvbC1sZy1vZmZlc3QtMVwiPlxuXHQ8ZGl2IGNsYXNzPVwianVtYm90cm9uXCI+XG5cdFx0PGgyPnt7IHRpdHVsbyB9fTwvaDI+XG5cdFx0PHA+TGEgcMOhZ2luYSBxdWUgaW50ZW50YXMgY2FyZ2FyIG5vIGV4aXN0ZS4gUHJ1ZWJhIGNvbiBlc3RvcyBib3RvbmVzOjwvcD5cblx0XHQ8cD5cblx0XHRcdDxhIFtyb3V0ZXJMaW5rXT1cIlsnL3Byb2R1Y3RvcyddXCIgY2xhc3M9XCJidG4gYnRuLWxnIGJ0bi1wcmltYXJ5XCI+VmVyIHByb2R1Y3RvczwvYT5cblx0XHRcdDxhIFtyb3V0ZXJMaW5rXT1cIlsnL2NyZWFyLXByb2R1Y3RvJ11cIiBjbGFzcz1cImJ0biBidG4tbGcgYnRuLXN1Y2Nlc3NcIj5Bw7FhZGlyIHByb2R1Y3RvczwvYT5cblx0XHQ8L3A+XG5cdDwvZGl2PlxuPC9kaXY+IiwiPGVycm9yPjwvZXJyb3I+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQUEsZ0JBQXNDLHdDQUNyQztNQUFBO01BQUEsOEJBQXVCLHlDQUN0QjthQUFBO1VBQUEsNENBQUk7TUFBQSxVQUFpQix5Q0FDckI7TUFBQTtNQUFBLDhCQUFHO01BQXNFLHlDQUN6RTtVQUFBO1VBQUEsZ0JBQUcsMENBQ0Y7VUFBQTtjQUFBO1lBQUE7WUFBQTtjQUFBO2tCQUFBO2NBQUE7WUFBQTtZQUFBO1VBQUEsdUNBQUE7VUFBQTtVQUFBLHNCQUFHLElBQTZEO01BQWlCLDBDQUNqRjtVQUFBO1VBQUE7WUFBQTtZQUFBO2NBQUE7a0JBQUE7Y0FBQTtZQUFBO1lBQUE7VUFBQSx1Q0FBQTtVQUFBO1VBQUEsc0JBQUcsSUFBa0U7TUFBb0IseUNBQ3RGO01BQ0M7SUFIRDtJQUFILFlBQUcsU0FBSDtJQUNHO0lBQUgsWUFBRyxTQUFIOzs7SUFKRztJQUFBO0lBR0g7SUFBQTtJQUFBLFlBQUEsbUJBQUE7SUFDQTtJQUFBO0lBQUEsWUFBQSxtQkFBQTs7OztvQkNOSDtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
