/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from '../../../../src/app/components/home.component';
const styles_HomeComponent:any[] = ([] as any[]);
export const RenderType_HomeComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_HomeComponent,data:{}});
export function View_HomeComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),23,'div',[['class',
      'col-lg-8 col-lg-offest-1']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n	'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),20,'div',[['class','jumbotron']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['',''])),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Gestiona tus productos con la aplicación web SPA creada con Angular desde cero'])),
      (_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          11,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n			'])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),3,'a',[['class','btn btn-lg btn-primary']],[[1,
              'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,13).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),i0.ɵpad(1),(_l()(),i0.ɵted((null as any),['Ver productos'])),
      (_l()(),i0.ɵted((null as any),['\n			'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          3,'a',[['class','btn btn-lg btn-success']],[[1,'target',0],[8,'href',4]],
          [[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,18).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),i0.ɵpad(1),(_l()(),i0.ɵted((null as any),['Añadir productos'])),
      (_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵted((null as any),['\n	'])),
      (_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    const currVal_3:any = _ck(_v,14,0,'/productos');
    _ck(_v,13,0,currVal_3);
    const currVal_6:any = _ck(_v,19,0,'/crear-producto');
    _ck(_v,18,0,currVal_6);
  },(_ck,_v) => {
    var _co:i3.HomeComponent = _v.component;
    const currVal_0:any = _co.titulo;
    _ck(_v,5,0,currVal_0);
    const currVal_1:any = i0.ɵnov(_v,13).target;
    const currVal_2:any = i0.ɵnov(_v,13).href;
    _ck(_v,12,0,currVal_1,currVal_2);
    const currVal_4:any = i0.ɵnov(_v,18).target;
    const currVal_5:any = i0.ɵnov(_v,18).href;
    _ck(_v,17,0,currVal_4,currVal_5);
  });
}
export function View_HomeComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'home',([] as any[]),
      (null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
      i0.ɵdid(114688,(null as any),0,i3.HomeComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const HomeComponentNgFactory:i0.ComponentFactory<i3.HomeComponent> = i0.ɵccf('home',
    i3.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3Jlc3RyYWRhei9hbmd1bGFyLXdlYnBhY2svd2VicGFjay1hbmd1bGFyNC9zcmMvYXBwL2NvbXBvbmVudHMvaG9tZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvcmVzdHJhZGF6L2FuZ3VsYXItd2VicGFjay93ZWJwYWNrLWFuZ3VsYXI0L3NyYy9hcHAvY29tcG9uZW50cy9ob21lLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL3Jlc3RyYWRhei9hbmd1bGFyLXdlYnBhY2svd2VicGFjay1hbmd1bGFyNC9zcmMvYXBwL3ZpZXdzL2hvbWUuaHRtbCIsIm5nOi8vL1VzZXJzL3Jlc3RyYWRhei9hbmd1bGFyLXdlYnBhY2svd2VicGFjay1hbmd1bGFyNC9zcmMvYXBwL2NvbXBvbmVudHMvaG9tZS5jb21wb25lbnQudHMuSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjb2wtbGctOCBjb2wtbGctb2ZmZXN0LTFcIj5cblx0PGRpdiBjbGFzcz1cImp1bWJvdHJvblwiPlxuXHRcdDxoMj57eyB0aXR1bG8gfX08L2gyPlxuXHRcdDxwPkdlc3Rpb25hIHR1cyBwcm9kdWN0b3MgY29uIGxhIGFwbGljYWNpw7NuIHdlYiBTUEEgY3JlYWRhIGNvbiBBbmd1bGFyIGRlc2RlIGNlcm88L3A+XG5cdFx0PHA+XG5cdFx0XHQ8YSBbcm91dGVyTGlua109XCJbJy9wcm9kdWN0b3MnXVwiIGNsYXNzPVwiYnRuIGJ0bi1sZyBidG4tcHJpbWFyeVwiPlZlciBwcm9kdWN0b3M8L2E+XG5cdFx0XHQ8YSBbcm91dGVyTGlua109XCJbJy9jcmVhci1wcm9kdWN0byddXCIgY2xhc3M9XCJidG4gYnRuLWxnIGJ0bi1zdWNjZXNzXCI+QcOxYWRpciBwcm9kdWN0b3M8L2E+XG5cdFx0PC9wPlxuXHQ8L2Rpdj5cbjwvZGl2PiIsIjxob21lPjwvaG9tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQSxnQkFBc0Msd0NBQ3JDO01BQUE7TUFBQSw4QkFBdUIseUNBQ3RCO2FBQUE7VUFBQSw0Q0FBSTtNQUFBLFVBQWlCLHlDQUNyQjtNQUFBO01BQUEsOEJBQUc7TUFBa0YseUNBQ3JGO1VBQUE7VUFBQSxnQkFBRywwQ0FDRjtVQUFBO2NBQUE7WUFBQTtZQUFBO2NBQUE7a0JBQUE7Y0FBQTtZQUFBO1lBQUE7VUFBQSx1Q0FBQTtVQUFBO1VBQUEsc0JBQUcsSUFBNkQ7TUFBaUIsMENBQ2pGO1VBQUE7VUFBQTtZQUFBO1lBQUE7Y0FBQTtrQkFBQTtjQUFBO1lBQUE7WUFBQTtVQUFBLHVDQUFBO1VBQUE7VUFBQSxzQkFBRyxJQUFrRTtNQUFvQix5Q0FDdEY7TUFDQztJQUhEO0lBQUgsWUFBRyxTQUFIO0lBQ0c7SUFBSCxZQUFHLFNBQUg7OztJQUpHO0lBQUE7SUFHSDtJQUFBO0lBQUEsWUFBQSxtQkFBQTtJQUNBO0lBQUE7SUFBQSxZQUFBLG1CQUFBOzs7O29CQ05IO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7In0=
