/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from '../../../../src/app/dashboard/dash.component';
const styles_DashboardComponent:any[] = ([] as any[]);
export const RenderType_DashboardComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_DashboardComponent,data:{}});
export function View_DashboardComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),[' Dashboard '])),(_l()(),i0.ɵted((null as any),['\n\n\n'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),8,'ul',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),5,'li',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),2,'a',[['class','boxCerrar iconswitch'],['routerLink','/contacto']],
          [[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,8).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i0.ɵted((null as any),['\n            contacto\n        '])),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),['\n']))],
      (_ck,_v) => {
        const currVal_2:any = '/contacto';
        _ck(_v,8,0,currVal_2);
      },(_ck,_v) => {
        const currVal_0:any = i0.ɵnov(_v,8).target;
        const currVal_1:any = i0.ɵnov(_v,8).href;
        _ck(_v,7,0,currVal_0,currVal_1);
      });
}
export function View_DashboardComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-dashboard',
      ([] as any[]),(null as any),(null as any),(null as any),View_DashboardComponent_0,
      RenderType_DashboardComponent)),i0.ɵdid(114688,(null as any),0,i3.DashboardComponent,
      [i1.Router],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const DashboardComponentNgFactory:i0.ComponentFactory<i3.DashboardComponent> = i0.ɵccf('my-dashboard',
    i3.DashboardComponent,View_DashboardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3Jlc3RyYWRhei9hbmd1bGFyLXdlYnBhY2svd2VicGFjay1hbmd1bGFyNC9zcmMvYXBwL2Rhc2hib2FyZC9kYXNoLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9yZXN0cmFkYXovYW5ndWxhci13ZWJwYWNrL3dlYnBhY2stYW5ndWxhcjQvc3JjL2FwcC9kYXNoYm9hcmQvZGFzaC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9yZXN0cmFkYXovYW5ndWxhci13ZWJwYWNrL3dlYnBhY2stYW5ndWxhcjQvc3JjL2FwcC9kYXNoYm9hcmQvdGVtcGxhdGUvZGFzaGJvYXJkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvcmVzdHJhZGF6L2FuZ3VsYXItd2VicGFjay93ZWJwYWNrLWFuZ3VsYXI0L3NyYy9hcHAvZGFzaGJvYXJkL2Rhc2guY29tcG9uZW50LnRzLkRhc2hib2FyZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT4gRGFzaGJvYXJkIDwvaDE+XG5cblxuPHVsPlxuICAgIDxsaT5cbiAgICAgICAgPGEgcm91dGVyTGluaz1cIi9jb250YWN0b1wiIGNsYXNzPVwiYm94Q2VycmFyIGljb25zd2l0Y2hcIj5cbiAgICAgICAgICAgIGNvbnRhY3RvXG4gICAgICAgIDwvYT5cbiAgICA8L2xpPlxuPC91bD4iLCI8bXktZGFzaGJvYXJkPjwvbXktZGFzaGJvYXJkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBLGlDQUFnQjtNQUdwQjtVQUFBLDBEQUFJO1VBQUEsYUFDQTtVQUFBO01BQUksK0NBQ0E7VUFBQTtVQUFBO1lBQUE7WUFBQTtjQUFBO2tCQUFBO2NBQUE7WUFBQTtZQUFBO1VBQUEsdUNBQUE7VUFBQTtVQUFBLGVBQXVEO01BRW5ELDJDQUNIOztRQUhFO1FBQUgsV0FBRyxTQUFIOztRQUFBO1FBQUE7UUFBQSxXQUFBLG1CQUFBOzs7O29CQ0xSO01BQUE7bUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
