/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from '../../../../src/app/contacto/contacto.component';
const styles_ContactoComponent:any[] = ([] as any[]);
export const RenderType_ContactoComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ContactoComponent,data:{}});
export function View_ContactoComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),[' Contacto '])),(_l()(),i0.ɵted((null as any),['\n\n'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),8,'ul',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),5,'li',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),2,'a',[['class','boxCerrar iconswitch'],['routerLink','/dashboard']],
          [[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,8).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i0.ɵted((null as any),['\n            Dashboard\n        '])),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),['\n']))],
      (_ck,_v) => {
        const currVal_2:any = '/dashboard';
        _ck(_v,8,0,currVal_2);
      },(_ck,_v) => {
        const currVal_0:any = i0.ɵnov(_v,8).target;
        const currVal_1:any = i0.ɵnov(_v,8).href;
        _ck(_v,7,0,currVal_0,currVal_1);
      });
}
export function View_ContactoComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'contacto',([] as any[]),
      (null as any),(null as any),(null as any),View_ContactoComponent_0,RenderType_ContactoComponent)),
      i0.ɵdid(114688,(null as any),0,i3.ContactoComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ContactoComponentNgFactory:i0.ComponentFactory<i3.ContactoComponent> = i0.ɵccf('contacto',
    i3.ContactoComponent,View_ContactoComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3Jlc3RyYWRhei9hbmd1bGFyLXdlYnBhY2svd2VicGFjay1hbmd1bGFyNC9zcmMvYXBwL2NvbnRhY3RvL2NvbnRhY3RvLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9yZXN0cmFkYXovYW5ndWxhci13ZWJwYWNrL3dlYnBhY2stYW5ndWxhcjQvc3JjL2FwcC9jb250YWN0by9jb250YWN0by5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9yZXN0cmFkYXovYW5ndWxhci13ZWJwYWNrL3dlYnBhY2stYW5ndWxhcjQvc3JjL2FwcC9jb250YWN0by90ZW1wbGF0ZS9jb250YWN0by5odG1sIiwibmc6Ly8vVXNlcnMvcmVzdHJhZGF6L2FuZ3VsYXItd2VicGFjay93ZWJwYWNrLWFuZ3VsYXI0L3NyYy9hcHAvY29udGFjdG8vY29udGFjdG8uY29tcG9uZW50LnRzLkNvbnRhY3RvQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPiBDb250YWN0byA8L2gxPlxuXG48dWw+XG4gICAgPGxpPlxuICAgICAgICA8YSByb3V0ZXJMaW5rPVwiL2Rhc2hib2FyZFwiIGNsYXNzPVwiYm94Q2VycmFyIGljb25zd2l0Y2hcIj5cbiAgICAgICAgICAgIERhc2hib2FyZFxuICAgICAgICA8L2E+XG4gICAgPC9saT5cbjwvdWw+IiwiPGNvbnRhY3RvPjwvY29udGFjdG8+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFJO2FBQUEsZ0NBQWU7TUFFbkI7VUFBQSwwREFBSTtVQUFBLGFBQ0E7VUFBQTtNQUFJLCtDQUNBO1VBQUE7VUFBQTtZQUFBO1lBQUE7Y0FBQTtrQkFBQTtjQUFBO1lBQUE7WUFBQTtVQUFBLHVDQUFBO1VBQUE7VUFBQSxlQUF3RDtNQUVwRCwyQ0FDSDs7UUFIRTtRQUFILFdBQUcsU0FBSDs7UUFBQTtRQUFBO1FBQUEsV0FBQSxtQkFBQTs7OztvQkNKUjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
