/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/contacto/contacto.module';
import * as i2 from './contacto.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/platform-browser';
import * as i5 from '@angular/forms';
import * as i6 from '@angular/router';
import * as i7 from '../../../../src/app/contacto/contacto-routing.module';
import * as i8 from '../../../../src/app/contacto/contacto.component';
export const ContactoModuleNgFactory:i0.NgModuleFactory<i1.ContactoModule> = i0.ɵcmf(i1.ContactoModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ContactoComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i3.NgLocalization,
              i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
              i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵl,([] as any[])),i0.ɵmpd(4608,i4.DomSanitizer,i4.ɵe,[i3.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i4.DomSanitizer]),i0.ɵmpd(4608,
              i4.HAMMER_GESTURE_CONFIG,i4.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i4.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i4.ɵDomEventsPlugin(p0_0),new i4.ɵKeyEventsPlugin(p1_0),
                    new i4.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i3.DOCUMENT,i3.DOCUMENT,i3.DOCUMENT,i4.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i4.EventManager,i4.EventManager,[i4.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i4.ɵDomSharedStylesHost,i4.ɵDomSharedStylesHost,[i3.DOCUMENT]),
          i0.ɵmpd(4608,i4.ɵDomRendererFactory2,i4.ɵDomRendererFactory2,[i4.EventManager,
              i4.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i4.ɵDomRendererFactory2]),i0.ɵmpd(6144,i4.ɵSharedStylesHost,(null as any),
              [i4.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i4.Meta,i4.Meta,[i3.DOCUMENT]),i0.ɵmpd(4608,
              i4.Title,i4.Title,[i3.DOCUMENT]),i0.ɵmpd(4608,i5.ɵi,i5.ɵi,([] as any[])),
          i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,([] as any[])),i0.ɵmpd(1024,
              i0.ErrorHandler,i4.ɵa,([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any) => {
                return [i4.ɵc(p0_0,p0_1)];
              },[[2,i4.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i4.BrowserModule,i4.BrowserModule,[[3,i4.BrowserModule]]),i0.ɵmpd(512,
              i5.ɵba,i5.ɵba,([] as any[])),i0.ɵmpd(512,i5.FormsModule,i5.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i6.RouterModule,i6.RouterModule,[[2,i6.ɵa],
              [2,i6.Router]]),i0.ɵmpd(512,i7.ContactoRouting,i7.ContactoRouting,([] as any[])),
          i0.ɵmpd(512,i1.ContactoModule,i1.ContactoModule,([] as any[])),i0.ɵmpd(1024,
              i6.ROUTES,() => {
                return [[{path:'contacto',component:i8.ContactoComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3Jlc3RyYWRhei9hbmd1bGFyLXdlYnBhY2svd2VicGFjay1hbmd1bGFyNC9zcmMvYXBwL2NvbnRhY3RvL2NvbnRhY3RvLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9yZXN0cmFkYXovYW5ndWxhci13ZWJwYWNrL3dlYnBhY2stYW5ndWxhcjQvc3JjL2FwcC9jb250YWN0by9jb250YWN0by5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
